# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Store.create(:name => "Aldo Accessories", :address => "N114 ")
Store.create(:name => "Chapel Hats", :address => "N170 ")
Store.create(:name => "Claire’s Boutique", :address => "E179 ")
Store.create(:name => "Francesca’s Collections", :address => "S116 ")
Store.create(:name => "GUESS Accessories", :address => "S130 ")
Store.create(:name => "Henri Bendel", :address => "S156 ")
Store.create(:name => "Local Charm a minnesota jewelry studio", :address => "S150 ")
Store.create(:name => "Michael Kors", :address => "S184 ")
Store.create(:name => "Piercing Pagoda", :address => "South 1 ")
Store.create(:name => "Solstice Sunglass Boutique", :address => "W131 ")
Store.create(:name => "Swatch", :address => "E162 ")
Store.create(:name => "Athleta", :address => "S145 ")
Store.create(:name => "Custom College Shop", :address => "E100 ")
Store.create(:name => "Footaction USA", :address => "E102 ")
Store.create(:name => "Foot Locker", :address => "N162 ")
Store.create(:name => "Hat World", :address => "E178 ")
Store.create(:name => "Hockey Minnesota by Goldy’s Locker Room", :address => "E160 ")
Store.create(:name => "Lids", :address => "E134 ")
Store.create(:name => "lululemon athletica", :address => "S152 ")
Store.create(:name => "Puma", :address => "N106 ")
Store.create(:name => "Vikings Locker Room", :address => "W160 ")
Store.create(:name => "Burberry ", :address => "S178")
Store.create(:name => "Carhartt", :address => "N144")
Store.create(:name => "Club Monaco", :address => "N102")
Store.create(:name => "Columbia Sportswear", :address => "W117")
Store.create(:name => "Desigual", :address => "S144")
Store.create(:name => "Forever 21", :address => "E144")
Store.create(:name => "Gap", :address => "S110")
Store.create(:name => "H&M", :address => "W117")
Store.create(:name => "Hot Topic", :address => "N168")
Store.create(:name => "Lacoste", :address => "S172")
Store.create(:name => "Lucky Brand kids", :address => "S170")
Store.create(:name => "Gymboree ", :address => "S154 ")
Store.create(:name => "Hanna Andersson", :address => "N190 ")
Store.create(:name => "Ivivva", :address => "S143 ")
Store.create(:name => "Janie & Jack", :address => "S168 ")
Store.create(:name => "Justice", :address => "N134 ")
Store.create(:name => "Boss Hugo Boss", :address => "S176 ")
Store.create(:name => "A/X Armani Exchange", :address => "S141")
Store.create(:name => "Banana Republic", :address => "W100")
Store.create(:name => "p.s. from aeropostale", :address => "N118 ")
Store.create(:name => "American Eagle Outfitters", :address => "S120 ")
Store.create(:name => "American Apparel", :address => "N186")
Store.create(:name => "bebe", :address => "N104")
Store.create(:name => "Caché", :address => "W132")
Store.create(:name => "Charlotte Russe", :address => "E141")
Store.create(:name => "Chico’s ", :address => "S160")
Store.create(:name => "Coldwater Creek", :address => "S166")
Store.create(:name => "Deb/Deb Plus", :address => "N151")
Store.create(:name => "Nike", :address => "S142 ")
Store.create(:name => "Oakley", :address => "N107 ")
Store.create(:name => "Old Navy Clothing", :address => "E138 ")
Store.create(:name => "Ragstock II", :address => "N124 ")
Store.create(:name => "Superdry", :address => "S142 ")
Store.create(:name => "True Religion Brand Jeans", :address => "S174 ")
Store.create(:name => "Urban Outfitters", :address => "W122 ")
Store.create(:name => "Victorinox Swiss Army", :address => "S138 ")
Store.create(:name => "Coffee Bean & Tea Leaf", :address => "E144")
Store.create(:name => "Garage", :address => "N140")
Store.create(:name => "Juicy Couture", :address => "S140")
Store.create(:name => "LOFT", :address => "N184")
Store.create(:name => "Wet Seal", :address => "N159")
Store.create(:name => "The White House Black Market", :address => "S148 ")
Store.create(:name => "Barnes & Noble", :address => "E118")
Store.create(:name => "Caribou Coffee", :address => "N194")
Store.create(:name => "American Girl", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "Nickelodeon Store", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "NU STUFF ", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "Peeps and Company", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "Caribou Coffee", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "COOL TREATS", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "Schwan’s Ice Cream ", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "TOYS", :address => "NICKELODEON UNIVERSE")
Store.create(:name => "Cinnabon ", :address => "E180 ")
Store.create(:name => "Soma Intimates ", :address => "W135 ")
Store.create(:name => "Progressions Aveda Salon", :address => "W135 ")
Store.create(:name => "Torrid", :address => "N148 ")
Store.create(:name => "Victoria’s Secret", :address => "N178 ")
Store.create(:name => "Holiday Station Store", :address => "W123 ")
Store.create(:name => "Street Corner News", :address => "E122 ")
Store.create(:name => "Macy’s ", :address => "SW Court ")
Store.create(:name => "Nordstrom", :address => "NW Court ")
Store.create(:name => "Sears", :address => "NE Court ")
Store.create(:name => "The LEGO® Store", :address => "S164 ")
Store.create(:name => "SEALIFE Minnesota Aquarium", :address => "E120 ")
Store.create(:name => "Rainforest Café", :address => "S102 ")
Store.create(:name => "Tucci Benucch", :address => "W114 ")
Store.create(:name => "The Magic Pan Crepe Stand", :address => "W114 ")
Store.create(:name => "Twin City Grill", :address => "N130 ")
Store.create(:name => "Orange Julius", :address => "W130")
Store.create(:name => "Rocky Mountain Chocolate Factory", :address => "E128")
Store.create(:name => "Freshens Yogurt", :address => "N126")
Store.create(:name => "Godiva Chocolatier", :address => "W126 ")
Store.create(:name => "Häagen Dazs", :address => "E130")
Store.create(:name => "icandy Sugar Shoppe", :address => "E154")
Store.create(:name => "Nestlé Toll House Café", :address => "W152")
Store.create(:name => "Starbucks Coffee", :address => "E164")
Store.create(:name => "Teavana", :address => "W128")
Store.create(:name => "Art of Shaving", :address => "W125")
Store.create(:name => "Mall of America Gift Store", :address => "E110")
Store.create(:name => "bareMinerals", :address => "E110")
Store.create(:name => "Bath & Body", :address => "N172")
Store.create(:name => "Blast Blow Dry Bar", :address => "S126")
Store.create(:name => "The Body Shop", :address => "W148")
Store.create(:name => "Intelligent Nutrients", :address => "S158")
Store.create(:name => "LUSH", :address => "E112")
Store.create(:name => "Regis Salon", :address => "E152")
Store.create(:name => "Sabon", :address => "W166")
Store.create(:name => "Brookstone", :address => "W162")
Store.create(:name => "Build-A-Bear Workshop®", :address => "E172")
Store.create(:name => "Disney Store ", :address => "S118")
Store.create(:name => "Field of Dreams", :address => "E156")
Store.create(:name => "Mall of America Gift Store", :address => "N128")
Store.create(:name => "Minnesot-ah!", :address => "E157")
Store.create(:name => "Papyrus", :address => "W158")
Store.create(:name => "Typo", :address => "N132")
Store.create(:name => "Traeger Wood Pellet Grills", :address => "West 1 ")
Store.create(:name => "Ben Bridge Jewelers", :address => "W136 ")
Store.create(:name => "Goodman Jewelers", :address => "N174 ")
Store.create(:name => "Helzberg Diamonds", :address => "W154 ")
Store.create(:name => "Kay Jewelers", :address => "N174 ")
Store.create(:name => "Macy’s Fine Jewelry", :address => "Level 1 ")
Store.create(:name => "Nordstrom Fine Jewelry", :address => "Level 1 ")
Store.create(:name => "Maria Rivolta", :address => "SE Court ")
Store.create(:name => "Pandora Jewelry", :address => "N127 ")
Store.create(:name => "Rogers and Hollands", :address => "W146 ")
Store.create(:name => "Lincoln Road Travelwear", :address => "W161 ")
Store.create(:name => "Tumi", :address => "W140 ")
Store.create(:name => "Apple", :address => "S132 ")
Store.create(:name => "Best Buy Mobile", :address => "E148 ")
Store.create(:name => "Bose", :address => "W156 ")
Store.create(:name => "Cellairis", :address => "North 1 ")
Store.create(:name => "Microsoft", :address => "S162 ")
Store.create(:name => "Glamour Kids", :address => "E108 ")
Store.create(:name => "Glamour Shots", :address => "E104 ")
Store.create(:name => "Stitch It", :address => "E132 ")
Store.create(:name => "Aldo", :address => "N188 ")
Store.create(:name => "Bostonian Shoes", :address => "W133 ")
Store.create(:name => "Call It Spring", :address => "N166 ")
Store.create(:name => "Clarks of England/Bostonian", :address => "E146 ")
Store.create(:name => "Crocs", :address => "N108 ")
Store.create(:name => "Dr. Martens", :address => "N101 ")
Store.create(:name => "D.S.W. Shoe Warehouse", :address => "W124 ")
Store.create(:name => "Johnston & Murphy", :address => "W144 ")
Store.create(:name => "Journeys", :address => "N154 ")
Store.create(:name => "Payless Shoe Source", :address => "N150 ")
Store.create(:name => "Steve Madden Shoes", :address => "W142 ")
Store.create(:name => "Stuart Weitzman", :address => "S180 ")
Store.create(:name => "The Walking Company", :address => "S108 ")
Store.create(:name => "Kiehl’s", :address => "N124 ")